// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA9YpahcAe5mmCCbcBM4Lu6hgH9sezzhE',
    appId: '1:1049278511789:web:072e3f83bfb96cbfe82424',
    messagingSenderId: '1049278511789',
    projectId: 'shirahsoft',
    authDomain: 'shirahsoft.firebaseapp.com',
    storageBucket: 'shirahsoft.firebasestorage.app',
    measurementId: 'G-3WC4402SSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlreWGmAS8yJdGrLg1ZhSuFNvfO4gid7g',
    appId: '1:1049278511789:android:1e03c52a63636453e82424',
    messagingSenderId: '1049278511789',
    projectId: 'shirahsoft',
    storageBucket: 'shirahsoft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz69IXjh79lVKmj21ZnzSLodYEpnzYg-0',
    appId: '1:1049278511789:ios:138b58452b6b0d36e82424',
    messagingSenderId: '1049278511789',
    projectId: 'shirahsoft',
    storageBucket: 'shirahsoft.firebasestorage.app',
    iosClientId: '1049278511789-b8s865gl7klpimvuusbvf0ddm38b18un.apps.googleusercontent.com',
    iosBundleId: 'com.shirahsoft.app',
  );

}